[package]
name = "acuity-atomic-swap-offchain"
version = "0.1.0"
edition = "2018"

[dependencies]
substrate-subxt = { git = "https://github.com/paritytech/substrate-subxt", branch = "aj-deps" }
web3 = "0.16.0"
rocksdb = "0.16.0"
tokio-tungstenite = "*"
tokio = { version = "1.0", features = ["full"] }
