[package]
name = "acuity-atomic-swap-offchain"
version = "0.1.0"
edition = "2018"

[dependencies]
substrate-api-client = { git = "https://github.com/scs/substrate-api-client", branch = "master" }
web3 = "0.16.0"
rocksdb = "0.16.0"
tokio-tungstenite = "*"
tokio = { version = "1.0", features = ["full"] }
codec = { package = "parity-scale-codec", features = ["derive"], version = "2.0.0" }

[dependencies.keyring]
git = "https://github.com/paritytech/substrate.git"
branch = "master"
package = "sp-keyring"

[dependencies.sp-runtime]
git = "https://github.com/paritytech/substrate.git"
branch = "master"
package = "sp-runtime"
default-features=false
