[package]
name = "acuity-atomic-swap-offchain"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
substrate-api-client = { git = "https://github.com/scs/substrate-api-client", branch = "master" }
web3 = "0.16.0"
rocksdb = "0.16.0"
